# Generated by Django 5.1.2 on 2024-10-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_pedido_detallepedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario1",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
    ]
