# Generated by Django 5.1.2 on 2024-10-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_usuario1"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario1",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
