# Generated by Django 5.1.2 on 2024-10-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_usuario1_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario1",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
