# Generated by Django 5.1.2 on 2024-10-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_usuario1_groups_usuario1_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario1",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
    ]
