# Generated by Django 5.1.2 on 2024-10-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_alter_usuario1_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="detalles",
            field=models.ManyToManyField(
                blank=True, related_name="pedidos", to="manager.detallepedido"
            ),
        ),
        migrations.AlterField(
            model_name="detallepedido",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detallesPedido",
                to="manager.pedido",
            ),
        ),
    ]
